theme = "tokyonight"

[editor]
true-color = true
bufferline = "multiple"
line-number = "relative"
cursorline = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
auto-format = true
completion-timeout = 5
completion-trigger-len = 1
completion-replace = true
idle-timeout = 400

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"
max-wrap = 5

[editor.file-picker]
hidden = false
git-ignore = true
ignore = true

[editor.soft-wrap]
enable = true

[editor.statusline]
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.lsp]
display-progress-messages = true

[keys.insert]
"A-n" = "normal_mode"
"A-l" = "move_char_right"
"A-h" = "move_char_left"
"A-j" = "move_visual_line_down"
"A-k" = "move_visual_line_up"
"A-o" = "open_below"
"A-O" = "open_above"
"A-u" = "undo"
"A-a" = "insert_at_line_end"
"A-i" = "insert_at_line_start"
